blank_issues_enabled: true
contact_links:
  - name: Ask on Discord
    url: https://discord.gg/BnfFZske
    about: For installation, setup, and usage questions, please ask in the Discord forum first for faster help.
